### ISSUE TITLE
[Bug]: Unable to pull down docker.

### ISSUE THREAD

**Issue by IronBeardKnight** [Sygil-Dev/sygil-webui#1817]
### What happened?

When trying to pull down docker on unraid  

docker: Error response from daemon: pull access denied for hlky/sd-webui, repository does not exist or may require 'docker login': denied: requested access to the resource is denied.

### Version

0.0.1 (Default)

### What browsers are you seeing the problem on?

Firefox, Chrome, Safari, Microsoft Edge

### Where are you running the webui?

Linux

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by yiqiangjun** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by ZeroCool940711** [comment]
@IronBeardKnight I've updated the [documentation](https://sygil-dev.github.io/sygil-webui/docs/Installation/docker-guide) for running the Sygil WebUI with docker, thanks to one of our users we built and uploaded a version of the Sygil WebUI to docker hub and its hosted on my own account in there, try using `tukirito/sygil-webui` instead of `hlky/sd-webui`.

**Comment by IronBeardKnight** [comment]
That you did I just found on the forums apologies. Might we expect an updated unraid docker in near future. Also thank you so much for the reply it's working again 🙏

**Comment by ZeroCool940711** [comment]
The docker image can be built from the repo code manually, check the docs [here](https://sygil-dev.github.io/sygil-webui/docs/Installation/docker-guide#building-the-image) for more info on how to do that. The issue is keeping the image up to date on docker hub with the changes from the repo, we tried several things such as using GitHub actions to try to build the image and upload it to docker hub but it didn't work, I think it was a paid feature, can't remember if it was on Github or docker hub itself and there doesn't seem to be a way to work around that unless we pay for that, I personally don't have funds for paying a subscription since I don't have any sort of income or I would gladly do so, it would be nice if we could just setup a github action and build the image when changes are pushed to the main branch.
